objects = [
    "Elephant", "Bicycle", "Pizza", "Sunrise", "Guitar", "Dancing", "Beach", "Computer",
    "Moonlight", "Television", "Sunglasses", "Bookshelf", "Basketball", "Train", "Robot",
    "Ice Cream", "Scissors", "Kangaroo", "Gardening", "Surfing", "Clock", "Picnic", "Castle",
    "Rollercoaster", "Fisherman", "Helicopter", "Cupcake", "Backpack", "Hot Air Balloon",
    "Snorkeling", "Carriage", "Campfire", "Pirate", "Astronaut", "Waterfall", "Yoga",
    "Racecar", "Telescope", "Windmill", "Wizard", "Ice Skating", "Map", "Detective", "Rainbow",
    "UFO", "Juggling", "Tornado", "Koala", "Trampoline", "Mermaid"
]
action_verbs = [
    "whispering","juggling","skiing",
    "gardening",
    "singing",
    "whistling",
    "sneezing",
    "painting",
    "fishing",
    "climbing",
    "boxing",
    "meditating",
    "marching",
    "driving",
    "yawning",
    "stretching",
    "diving",
    "shaving",
    "wrestling",
    "dancing",
    "shuffling",
    "shivering",
    "bouncing",
    "skipping",
    "winking",
    "stirring",
    "saluting",
    "tumbling",
    "sweeping",
    "flipping",
    "typing",
    "peeking",
    "giggling",
    "snapping",
    "spinning",
    "shouting",
    "snoring",
    "waving",
    "kicking",
    "hiking",
    "pointing",
    "fainting",
    "gulping",
    "thumbing",
    "twitching",
    "applauding",
    "tiptoeing",
    "nudging",
    "grinning"
]
places = [
    "Library",
    "Cemetery",
    "Subway station",
    "Waterfall",
    "Casino",
    "Lighthouse",
    "Amusement park",
    "Junkyard",
    "Bakery",
    "Bus stop",
    "Airport",
    "Ski resort",
    "Skyscraper",
    "Post office",
    "Farmhouse",
    "Gas station",
    "Windmill",
    "Diner",
    "Harbor",
    "Campsite",
    "Waterpark",
    "Observatory",
    "Museum",
    "Cottage",
    "Downtown",
    "Warehouse",
    "Aquarium",
    "Pagoda",
    "Vineyard",
    "Canal",
    "Cave",
    "Golf course",
    "Rooftop",
    "City square",
    "Tavern",
    "Fountain",
    "Train station",
    "Gondola",
    "Rodeo arena",
    "Greenhouse",
    "Reservoir",
    "Wind farm",
    "Boutique",
    "Alleyway",
    "Fish market",
    "Race track",
    "Cityscape",
    "Volcano"
]
african_animals = [
    "Lion",
    "Elephant",
    "Giraffe",
    "Zebra",
    "Cheetah",
    "Hippopotamus",
    "Rhino",
    "Gorilla",
    "Leopard",
    "Crocodile",
    "Buffalo",
    "Hyena",
    "Wildebeest",
    "Meerkat",
    "Giraffe",
    "Monkey",
    "Gazelle",
    "Ostrich",
    "Baboon",
    "Warthog",
    "Impala",
    "Pangolin",
    "Aardvark",
    "African Wild Dog",
    "Okapi",
    "Chimpanzee",
    "Springbok",
    "Dung Beetle",
    "Fennec Fox",
    "Honey Badger",
    "African Grey Parrot",
    "Nile Crocodile",
    "Vulture",
    "Secretary Bird",
    "Fossa",
    "African Penguin",
    "African Rock Python",
    "Cape Buffalo",
    "African Elephant",
    "Hornbill",
    "Red Colobus Monkey",
    "African Civet",
    "Caracal",
    "Genet",
    "Serval",
    "Rock Hyrax",
    "Black Mamba",
    "Monitor Lizard"
]
random_ = [
    "guitar", "waterfall", "movie", "violin", "mountain", "karaoke",
    "trumpet", "forest", "comedy", "piano", "sunflower", "concert",
    "drum", "beach"
    
    
    
    , "dance", "flute", "rainforest", "game", "saxophone",
    "cactus", "theater", "jazz", "accordion", "ocean", "celebration",
    "harmonica", "valley", "camera", "bass", "butterfly", "magic",
    "keyboard", "desert", "quiz", "harp", "lake", "popcorn", "trombone",
    "banjo", "star", "circus", "ukulele", "moon", "festival", "clarinet",
    "volcano", "museum", "fireworks", "xylophone"
]